[versions]
# Plugins
agp = "8.7.2"
kotlin = "2.0.21"

# AndroidX & UI
androidx-appcompat = "1.7.0"
androidx-recyclerview = "1.3.2"
google-material = "1.12.0"
glide = "4.16.0"
coil = "3.0.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }
android-lib = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
